name: 💡 Feature Request (Suggestion)
description: Create a feature request to enhance the experience using Tidy Tab Groups.
title: 'Your Descriptive Title'
labels: ['enhancement']
assignees: elouangrimm,MoeBazziGIT
body:
    - type: markdown
      attributes:
          value: |
              Please fill out the sections below to properly describe the new feature you are suggesting.

              Thank you for taking the time to create this feature request.

    - type: checkboxes
      id: duplicates
      attributes:
          label: Prerequisites
          description: Increase the chances of your idea being accepted by making sure it has not been raised before.
          options:
              - label: I [searched for any existing report](https://github.com/TidyTabGroups/TidyTabGroups/labels/enhancement) about this feature to avoid opening a duplicate.
                required: true
              - label: "This issue contains **only one feature request**. (hint: make multiple reports, it makes it easier on our end!)"
                required: true
              - label: The title of this issue **accurately** describes the bug.
                required: true

    - type: textarea
      id: description
      attributes:
          label: Feature Request Description
          description: Provide a clear and concise description of this feature request with any problems and solutions.
          placeholder: A button in the screen X that allows to do Y
      validations:
          required: true

    - type: textarea
      id: rationale
      attributes:
          label: Use Case
          description: It should be implemented because...? Provide a scenario or use case for this feature, if applicable.
          placeholder: It will allow to do Y that is needed for Z
      validations:
          required: true

    - type: textarea
      id: screenshots
      attributes:
          label: Screenshots or Videos
          description: Add screenshots or video to help explain this feature request, if applicable.
      validations:
          required: false

    - type: textarea
      id: context
      attributes:
          label: Additional context
          description: Provide any additional information about this feature request.
      validations:
          required: false

    - type: markdown
      attributes:
          value: |
              ### Thank you so much for your suggestion! 🙏 Your input helps us improve the browser extension. 🫂
